import type { Metadata} from "next";
import {Aboreto, Gasoek_One, Inter, Michroma} from '@next/font/google'
import localFont from "next/font/local";
import "./globals.css";


/*-------
 * FONTS*
 *------*/
const inter = Inter({
  subsets:['latin'],
  weight: ['100','300','900'],
  variable:'--font-inter'
})
const gasoekONE = Gasoek_One({
  subsets:['latin'],
  weight:"400",
  variable:'--font-gasoekONE'
})

const aboreto = Aboreto({
  subsets:["latin"],
  weight:"400",
  variable: '--font-aboreto'
})
const michroma = Michroma({
  subsets: ["latin"],
  weight: "400",
  variable:'--font-michroma'
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
/**********************************/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} 
          ${geistMono.variable} 
          ${michroma.variable}
          ${aboreto.variable}
          ${gasoekONE.variable}
          ${inter.variable}
          antialiased`}
          
          style={{fontFamily:'var(--font-inter)'}}
      >
        {children}
      </body>
    </html>
  );
}
